### ISSUE TITLE
Parameterized or Parametrized?

### ISSUE THREAD

**Issue by mikeingold** [JuliaGeometry/MeshIntegrals.jl#143]
We should pick a spelling and stick to it. Meshes currently defines a `Parametrized` but I've mostly used `Parameterized` here. Looking for feedback on preferences.

**Comment by JoshuaLampert** [comment]
Since we cannot really easily change `ParametrizedCurve` as it comes from Meshes.jl, I would opt going for `parametrized` and `parametrizing` everywhere. Currently, there seem to be [8 occurrences](https://github.com/search?q=repo%3AJuliaGeometry%2FMeshIntegrals.jl+parameteri&type=code) we would need to change.
